### ISSUE TITLE
`multipleResolves` not part of v2 release?

### ISSUE THREAD

**Issue by exequiel09** [mcollina/make-promises-safe#11]
I have seen the codebase and commits in #8 mentioning that it includes `multipleResolves` event but in the version 2 which is available in NPM, it does not include the event handling for `multipleResolves`. I can verify it by visiting the unpkg url for the package https://unpkg.com/make-promises-safe@2.0.0/make-promises-safe.js

Please confirm if it's not yet released. Thanks.

**Comment by mcollina** [comment]
I botched the release v3.0.0 coming up.
