### ISSUE TITLE
Add a "files" (whitelist) field to package.json ?

### ISSUE THREAD

**Issue by fraxken** [mcollina/make-promises-safe#15]
Hi,

I'm working on a security tool and i'v discovered that some files has been published in the tarball:
- example.js
- test.js
- .travis.yml

![](https://i.imgur.com/V5MczHU.png)

So because you'r using **http** in example.js my tool put a flag (the little planet). If there is no reason to publish these files, can you consider removing them for the next release ?

(to be added to the package.json)
```json
{
  "files": ["make-promises-safe.js"]
}
```

Thanks for your time and work.

Best Regards,
Thomas

**Comment by mcollina** [comment]
I’m sorry, but I think that a release includes documentation, tests and examples.
