### ISSUE TITLE
Question: Why the Warning about not using this in Reusable Modules?

### ISSUE THREAD

**Issue by astorm** [mcollina/make-promises-safe#17]
The `README.md` for this project currently contains the following warning

> It is important that this module is only used in top-level program code, not in reusable modules!

but does not (or does it?!) really explain _why_ it's important to only use this module in top level program code.  

Is this simply a best practice warning against surprising users by changing the behavior of their un-handled promise rejections via a third party module?  Or are there other, subtle problems with defining a process level `unhandledRejection` handler via reusable module code?

**Comment by mcollina** [comment]
> Is this simply a best practice warning against surprising users by changing the behavior of their un-handled promise rejections via a third party module?

Yes exactly. A module should not unexpectedly change the behavior of a global without notice.
