### ISSUE TITLE
Question about node v15 usage

### ISSUE THREAD

**Issue by DRoet** [mcollina/make-promises-safe#18]
Just so I understand correctly... since the the default mode for `unhandledRejection` is changed to `throw`, is it correct to say that this package is now no longer needed for newer versions?

**Comment by benjamingr** [comment]
Correct.

We've done it :) 🎉 

Might be a good idea to update the readme (cc @mcollina )

**Comment by mcollina** [comment]
We made it!

**Comment by benjamingr** [comment]
I opened a PR, the wording is a bit subjective - but since this isn't core I think we get to be honest.
