### ISSUE TITLE
make-promises-debuggable

### ISSUE THREAD

**Issue by davidmarkclements** [mcollina/make-promises-safe#2]
Suggestion for a sequel module: `make-promises-debuggable`

Might not be possible, but making a process crash when there's a syntax error
in a promise that already has a catch handler would be helpful for development experience

**Comment by BridgeAR** [comment]
With newer Node.js versions this is a bad idea as `async / await` is going to provide useful stack traces from now on.

And monkey patching promises is likely going to slow down all promises significantly.
