### ISSUE TITLE
Replace process.exit(1) with process.exitCode

### ISSUE THREAD

**Issue by idandagan1** [mcollina/make-promises-safe#9]
According to [Node.js recommendation](https://nodejs.org/api/process.html#process_process_exit_code):

> Calling process.exit() will force the process to exit as quickly as possible even if there are still asynchronous operations pending that have not yet completed fully, including I/O operations to process.stdout and process.stderr.
In most situations, it is not actually necessary to call process.exit() explicitly. The Node.js process will exit on its own if there is no additional work pending in the event loop. The process.exitCode property can be set to tell the process which exit code to use when the process exits gracefully..

if you think this is necessary I can create a PR.

**Comment by benjamingr** [comment]
> Calling process.exit() will force the process to exit as quickly as possible even if there are still asynchronous operations pending that have not yet completed fully, including I/O operations to process.stdout and process.stderr.

I think this is quite intentional.

**Comment by mcollina** [comment]
The use of process.exit(1) here is quite intentional, as this is not a graceful shutdown.
